# Generated by Django 4.2.10 on 2024-03-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_code', models.CharField(max_length=5)),
                ('car_model', models.CharField(max_length=15)),
            ],
        ),
    ]
